import AppKit
import os

extension Notification.Name {
    static let clipboardPanelReset = Notification.Name("clipboardPanelReset")
}

@MainActor
final class Paster {
    static let shared = Paster()

    private static let logger = Logger(subsystem: "dev.ilkome.MaCopy", category: "paste")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    private static let sourceType = NSPasteboard.PasteboardType("org.nspasteboard.source")
    private static let clipboardClearDelay: TimeInterval = 60

    var previousApp: NSRunningApplication?
    var didPaste = false

    private var activationObserver: NSObjectProtocol?
    private var activationTimer: DispatchWorkItem?
    private var clipboardClearTask: Task<Void, Never>?

    private init() {}

    @discardableResult
    func copyToPasteboard(_ item: ClipboardItemRecord) -> Bool {
        let pb = NSPasteboard.general
        switch item.kind {
        case .image:
            guard let path = item.imagePath,
                  let data = try? ImageStore.read(filename: path),
                  let image = NSImage(data: data),
                  image.isValid
            else { return false }
            pb.clearContents()
            guard pb.writeObjects([image]) else { return false }
        default:
            guard let text = item.text, !text.isEmpty else { return false }
            pb.clearContents()
            pb.setString(text, forType: .string)
        }
        let bundleId = Bundle.main.bundleIdentifier ?? "dev.ilkome.MaCopy"
        pb.setString(bundleId, forType: Self.sourceType)
        pb.setData(Data(), forType: Self.autoGeneratedType)
        scheduleClipboardClear()
        return true
    }

    private func scheduleClipboardClear() {
        clipboardClearTask?.cancel()
        let captured = NSPasteboard.general.changeCount
        let delay = Self.clipboardClearDelay
        clipboardClearTask = Task { @MainActor in
            try? await Task.sleep(for: .seconds(delay))
            guard !Task.isCancelled else { return }
            let pb = NSPasteboard.general
            guard pb.changeCount == captured else { return }
            pb.clearContents()
            Self.logger.info("pasteboard cleared after \(Int(delay), privacy: .public)s of inactivity")
        }
    }

    @discardableResult
    func copyOnly(_ item: ClipboardItemRecord) -> Bool {
        guard copyToPasteboard(item) else { return false }
        didPaste = true
        AppDelegate.shared?.hidePanel()
        return true
    }

    @discardableResult
    func paste(_ item: ClipboardItemRecord) -> Bool {
        guard copyToPasteboard(item) else { return false }

        didPaste = true
        AppDelegate.shared?.hidePanel()

        guard AccessibilityPrompt.isTrusted() else {
            AccessibilityPrompt.showAlert()
            return true
        }

        let ownPID = ProcessInfo.processInfo.processIdentifier
        if let prev = previousApp, prev.processIdentifier != ownPID, !prev.isActive {
            prev.activate(options: [])
            awaitActivation(of: prev) { activated in
                guard activated else {
                    Self.logger.info("paste aborted: activation timeout (pid=\(prev.processIdentifier, privacy: .private))")
                    return
                }
                let frontPID = NSWorkspace.shared.frontmostApplication?.processIdentifier
                guard frontPID == prev.processIdentifier else {
                    Self.logger.info("paste aborted: frontmost mismatch (expected=\(prev.processIdentifier, privacy: .private), got=\(frontPID ?? -1, privacy: .private))")
                    return
                }
                guard !PasteSimulator.isSecureInputEnabled() else {
                    Self.logger.info("paste aborted: secure input enabled")
                    return
                }
                PasteSimulator.simulateCmdV()
            }
        } else {
            guard !PasteSimulator.isSecureInputEnabled() else {
                Self.logger.info("paste aborted: secure input enabled")
                return true
            }
            PasteSimulator.simulateCmdV()
        }
        return true
    }

    private func awaitActivation(
        of app: NSRunningApplication,
        timeout: TimeInterval = 0.3,
        completion: @escaping @MainActor (Bool) -> Void
    ) {
        cancelActivationWait()
        let center = NSWorkspace.shared.notificationCenter
        let targetPID = app.processIdentifier

        let finish: @MainActor (Bool) -> Void = { [weak self] activated in
            guard let self else { return }
            self.cancelActivationWait()
            completion(activated)
        }

        activationObserver = center.addObserver(
            forName: NSWorkspace.didActivateApplicationNotification,
            object: nil,
            queue: .main
        ) { notification in
            guard let running = notification
                .userInfo?[NSWorkspace.applicationUserInfoKey] as? NSRunningApplication,
                  running.processIdentifier == targetPID
            else { return }
            MainActor.assumeIsolated { finish(true) }
        }

        let work = DispatchWorkItem { MainActor.assumeIsolated { finish(false) } }
        activationTimer = work
        DispatchQueue.main.asyncAfter(deadline: .now() + timeout, execute: work)
    }

    private func cancelActivationWait() {
        if let observer = activationObserver {
            NSWorkspace.shared.notificationCenter.removeObserver(observer)
            activationObserver = nil
        }
        activationTimer?.cancel()
        activationTimer = nil
    }

}
