import AppKit
import os

extension Notification.Name {
    static let clipboardPanelReset = Notification.Name("clipboardPanelReset")
}

@MainActor
final class Paster {
    static let shared = Paster()

    struct Dependencies {
        var preparePasteboard: (@MainActor (ClipboardItemRecord) -> Bool)?
        var isTrusted: @MainActor () -> Bool = { AccessibilityPrompt.isTrusted() }
        var showAccessibilityAlert: @MainActor () -> Void = { AccessibilityPrompt.showAlert() }
        var hidePanel: @MainActor () -> Void = { AppDelegate.shared?.hidePanel() }
        var activateApplication: @MainActor (NSRunningApplication) -> Void = { $0.activate(options: []) }
        var awaitActivation: (@MainActor (
            NSRunningApplication,
            @escaping @MainActor (Bool) -> Void
        ) -> Void)?
        var frontmostPID: @MainActor () -> pid_t? = {
            NSWorkspace.shared.frontmostApplication?.processIdentifier
        }
        var dispatchPaste: @MainActor () -> Bool = { PasteSimulator.simulateCmdV() }
        var recordCopy: @MainActor (UUID) throws -> Void = { id in
            _ = try ClipboardItemRepository.recordCopy(id: id)
        }
        var recordPaste: @MainActor (UUID) throws -> Void = { id in
            _ = try ClipboardItemRepository.recordPaste(id: id)
        }
    }

    private static let logger = Logger(subsystem: "dev.ilkome.MaCopy", category: "paste")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    private static let sourceType = NSPasteboard.PasteboardType("org.nspasteboard.source")
    private static let clipboardClearDelay: TimeInterval = 60

    var previousApp: NSRunningApplication?

    private var activationObserver: NSObjectProtocol?
    private var activationTimer: DispatchWorkItem?
    private var clipboardClearTask: Task<Void, Never>?
    private var pasteRequestID: UInt64 = 0
    private let dependencies: Dependencies

    init(dependencies: Dependencies = Dependencies()) {
        self.dependencies = dependencies
    }

    @discardableResult
    func copyToPasteboard(_ item: ClipboardItemRecord) -> Bool {
        if let preparePasteboard = dependencies.preparePasteboard {
            return preparePasteboard(item)
        }
        let pb = NSPasteboard.general
        switch item.kind {
        case .image:
            guard let path = item.imagePath,
                  let data = try? ImageStore.read(filename: path),
                  let image = NSImage(data: data),
                  image.isValid
            else { return false }
            pb.clearContents()
            guard pb.writeObjects([image]) else { return false }
        default:
            // The list record carries only a capped text excerpt; load the full text
            // by id so long clips are pasted in full.
            let fullText = (try? ClipboardItemRepository.findItem(byID: item.id))?.text ?? item.text
            guard let text = fullText, !text.isEmpty else { return false }
            pb.clearContents()
            guard pb.setString(text, forType: .string) else { return false }
        }
        let bundleId = Bundle.main.bundleIdentifier ?? "dev.ilkome.MaCopy"
        guard pb.setString(bundleId, forType: Self.sourceType),
              pb.setData(Data(), forType: Self.autoGeneratedType),
              pb.data(forType: Self.autoGeneratedType) != nil
        else {
            pb.clearContents()
            return false
        }
        scheduleClipboardClear()
        return true
    }

    private func scheduleClipboardClear() {
        clipboardClearTask?.cancel()
        let captured = NSPasteboard.general.changeCount
        let delay = Self.clipboardClearDelay
        clipboardClearTask = Task { @MainActor in
            try? await Task.sleep(for: .seconds(delay))
            guard !Task.isCancelled else { return }
            let pb = NSPasteboard.general
            guard pb.changeCount == captured else { return }
            pb.clearContents()
            Self.logger.info("pasteboard cleared after \(Int(delay), privacy: .public)s of inactivity")
        }
    }

    @discardableResult
    func copyOnly(_ item: ClipboardItemRecord) -> Bool {
        guard copyToPasteboard(item) else { return false }
        recordCopyBestEffort(id: item.id)
        dependencies.hidePanel()
        return true
    }

    @discardableResult
    func paste(_ item: ClipboardItemRecord) -> Bool {
        pasteRequestID &+= 1
        let requestID = pasteRequestID
        cancelActivationWait()
        guard copyToPasteboard(item) else { return false }

        dependencies.hidePanel()

        guard dependencies.isTrusted() else {
            dependencies.showAccessibilityAlert()
            return true
        }

        let ownPID = ProcessInfo.processInfo.processIdentifier
        if let prev = previousApp, prev.processIdentifier != ownPID, !prev.isActive {
            dependencies.activateApplication(prev)
            let completion: @MainActor (Bool) -> Void = { [weak self] activated in
                guard let self, self.pasteRequestID == requestID else { return }
                guard activated else {
                    Self.logger.info("paste aborted: activation timeout (pid=\(prev.processIdentifier, privacy: .private))")
                    return
                }
                let frontPID = self.dependencies.frontmostPID()
                guard frontPID == prev.processIdentifier else {
                    Self.logger.info("paste aborted: frontmost mismatch (expected=\(prev.processIdentifier, privacy: .private), got=\(frontPID ?? -1, privacy: .private))")
                    return
                }
                if self.dependencies.dispatchPaste() {
                    self.recordPasteBestEffort(id: item.id)
                }
            }
            if let awaitActivation = dependencies.awaitActivation {
                awaitActivation(prev, completion)
            } else {
                awaitActivation(of: prev, completion: completion)
            }
        } else {
            if dependencies.dispatchPaste() {
                recordPasteBestEffort(id: item.id)
            }
        }
        return true
    }

    private func recordCopyBestEffort(id: UUID) {
        do { try dependencies.recordCopy(id) }
        catch { Self.logger.error("copy counter persistence failed: \(error, privacy: .private)") }
    }

    private func recordPasteBestEffort(id: UUID) {
        do { try dependencies.recordPaste(id) }
        catch { Self.logger.error("paste counter persistence failed: \(error, privacy: .private)") }
    }

    private func awaitActivation(
        of app: NSRunningApplication,
        timeout: TimeInterval = 0.3,
        completion: @escaping @MainActor (Bool) -> Void
    ) {
        cancelActivationWait()
        let center = NSWorkspace.shared.notificationCenter
        let targetPID = app.processIdentifier

        let finish: @MainActor (Bool) -> Void = { [weak self] activated in
            guard let self else { return }
            self.cancelActivationWait()
            completion(activated)
        }

        activationObserver = center.addObserver(
            forName: NSWorkspace.didActivateApplicationNotification,
            object: nil,
            queue: .main
        ) { notification in
            guard let running = notification
                .userInfo?[NSWorkspace.applicationUserInfoKey] as? NSRunningApplication,
                  running.processIdentifier == targetPID
            else { return }
            MainActor.assumeIsolated { finish(true) }
        }

        let work = DispatchWorkItem { MainActor.assumeIsolated { finish(false) } }
        activationTimer = work
        DispatchQueue.main.asyncAfter(deadline: .now() + timeout, execute: work)
    }

    private func cancelActivationWait() {
        if let observer = activationObserver {
            NSWorkspace.shared.notificationCenter.removeObserver(observer)
            activationObserver = nil
        }
        activationTimer?.cancel()
        activationTimer = nil
    }

}
