import AppKit

enum PrivacyFilter {
    static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "org.nspasteboard.TransientType",
        "com.agilebits.onepassword",
        "com.bitwarden.pasteboard",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type"
    ]

    @MainActor
    static func shouldIgnore(_ pb: NSPasteboard) -> Bool {
        guard let types = pb.types else { return false }
        for t in types where ignoredTypes.contains(t.rawValue) { return true }
        return false
    }
}
