import KeyboardShortcuts
import SwiftUI

struct SettingsView: View {
    @ObservedObject private var settings = AppSettings.shared
    var onBack: (() -> Void)? = nil

    var body: some View {
        VStack(spacing: 0) {
            header
            Divider().opacity(0.3)
            ScrollView {
                content
                    .padding(20)
            }
        }
    }

    @ViewBuilder
    private var header: some View {
        HStack(spacing: 10) {
            if let onBack {
                Button {
                    onBack()
                } label: {
                    Image(systemName: "chevron.left")
                        .font(.system(size: 13, weight: .medium))
                        .foregroundStyle(.secondary)
                }
                .buttonStyle(.borderless)
                .help("Назад")
            }
            Text("Настройки")
                .font(.system(size: 14, weight: .semibold))
            Spacer()
        }
        .padding(.horizontal, 18)
        .frame(height: Layout.searchHeight)
    }

    @ViewBuilder
    private var content: some View {
        VStack(alignment: .leading, spacing: 24) {
            section(title: "Поиск") {
                    Toggle(isOn: $settings.ocrEnabled) {
                        VStack(alignment: .leading, spacing: 2) {
                            Text("OCR для скриншотов")
                            Text("Распознаёт текст на изображениях и делает его искомым.")
                                .font(.system(size: 11))
                                .foregroundStyle(.secondary)
                        }
                    }
                }

                section(title: "Внешний вид") {
                    HStack {
                        Text("Плотность фона")
                        Spacer()
                        Picker("", selection: $settings.panelMaterial) {
                            ForEach(PanelMaterial.allCases) { option in
                                Text(option.title).tag(option)
                            }
                        }
                        .labelsHidden()
                        .frame(width: 160)
                    }
                }

                section(title: "Превью ссылок") {
                    Toggle(isOn: $settings.linkPreviewsEnabled) {
                        VStack(alignment: .leading, spacing: 2) {
                            Text("Показывать превью ссылок")
                            Text("Подгружает title, описание и картинку. Не работает для локальных/приватных адресов.")
                                .font(.system(size: 11))
                                .foregroundStyle(.secondary)
                        }
                    }
                }

                section(title: "Глобальный хоткей") {
                    HStack {
                        Text("Открыть панель")
                        Spacer()
                        KeyboardShortcuts.Recorder(for: .togglePanel)
                    }
                }

                section(title: "Клавиши в панели") {
                    VStack(alignment: .leading, spacing: 10) {
                        shortcutRow(label: "Навигация по списку", keys: ["↑", "↓"])
                        shortcutRow(label: "Переключение вкладок", keys: ["←", "→"])
                        shortcutRow(label: "Вставить в предыдущее окно", keys: ["⏎"])
                        shortcutRow(label: "Скопировать в буфер без вставки", keys: ["⇧", "⏎"])
                        shortcutRow(label: "Избранное", keys: ["⌘", "D"])
                        shortcutRow(label: "Удалить элемент", keys: ["⌘", "⌫"])
                        shortcutRow(label: "Quick Look для изображений", keys: ["␣"])
                        shortcutRow(label: "Скрыть панель", keys: ["⎋"])
                    }
                }

                section(title: "FAQ") {
                    VStack(alignment: .leading, spacing: 12) {
                        faqItem(
                            q: "Как разрешить автоматическую вставку?",
                            a: "Системные настройки → Приватность и безопасность → Универсальный доступ, включи MaCopy. Без этого содержимое копируется в буфер, но ⌘V симулироваться не будет."
                        )
                        faqItem(
                            q: "Где хранятся данные?",
                            a: "~/Library/Application Support/MaCopy. SwiftData SQLite-база + картинки в отдельных файлах."
                        )
                        faqItem(
                            q: "Как исключить приложение?",
                            a: "MaCopy уважает pasteboard.org-типы (ConcealedType, AutoGeneratedType, TransientType) и специфичные типы 1Password/Bitwarden."
                        )
                    }
                }
        }
    }

    private func shortcutRow(label: String, keys: [String]) -> some View {
        HStack {
            Text(label)
            Spacer()
            HStack(spacing: 4) {
                ForEach(keys, id: \.self) { key in
                    Text(key)
                        .font(.system(size: 12, weight: .medium, design: .monospaced))
                        .padding(.horizontal, 8)
                        .padding(.vertical, 3)
                        .background(
                            RoundedRectangle(cornerRadius: 5)
                                .fill(Color.primary.opacity(0.08))
                        )
                        .overlay(
                            RoundedRectangle(cornerRadius: 5)
                                .stroke(Color.primary.opacity(0.12))
                        )
                }
            }
        }
    }

    private func faqItem(q: String, a: String) -> some View {
        VStack(alignment: .leading, spacing: 4) {
            Text(q)
                .font(.system(size: 13, weight: .semibold))
            Text(a)
                .font(.system(size: 12))
                .foregroundStyle(.secondary)
                .fixedSize(horizontal: false, vertical: true)
        }
    }

    @ViewBuilder
    private func section<Content: View>(
        title: String,
        @ViewBuilder content: () -> Content
    ) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            Text(title)
                .font(.headline)
                .foregroundStyle(.secondary)
            content()
                .padding(12)
                .frame(maxWidth: .infinity, alignment: .leading)
                .background(
                    RoundedRectangle(cornerRadius: 8)
                        .fill(Color.primary.opacity(0.05))
                )
        }
    }
}
